config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#home"
  
  # Pages
  get 'home', to: 'pages#home', as: 'home'
  get 'index', to: 'pages#index'
  get 'boxing_gloves', to: 'pages#boxing_gloves', as: 'boxing_gloves'
  get 'punching_bags', to: 'pages#punching_bags', as: 'punching_bags'
  get 'apparel', to: 'pages#apparel', as: 'apparel'
  get 'search', to: 'pages#search', as: 'search'

  # Item
  get 'items/:id', to: 'item#show', as: 'item'
  get 'items', to: 'items#index', as: 'items'

  # Cart
  get 'cart', to: 'carts#show', as: 'cart'
  post 'items/:id/add_to_cart', to: 'cart_items#create', as: 'add_to_cart'

  # Cart Items
  get '/cart_items/:id/edit', to: 'cart_items#edit', as: 'cart_items_edit'
  delete '/cart_items/:id/', to: 'cart_items#delete', as: 'cart_items'
  patch '/cart_items/:id/', to: 'cart_items#update'

  # Payments
  get 'checkout', to: 'payment#new', as: 'new_payment'
  post 'payments', to: 'payment#create', as: 'create_payment'
  get 'payments/:id', to: 'payment#show', as: 'payment'
  get 'payments', to: 'payment#index', as: 'payments'

  # Reviews
  get 'items/:item_id/reviews', to: 'reviews#index', as: 'item_reviews'
  post 'items/:item_id/reviews', to: 'reviews#create'
  get 'items/:item_id/reviews/new', to: 'reviews#new', as: 'new_item_review'
  get 'items/:item_id/reviews/:id/edit', to: 'reviews#edit', as: 'edit_item_review'
  patch 'item/:item_id/reviews/:id', to: 'reviews#update', as: 'toedit'
  # get 'items/:item_id/reviews', to: 'reviews#show', as: 'item_review'
  delete 'items/:item_id/reviews/:id', to: 'reviews#destroy', as: 'delete_item_review'

  # Users
  get 'user/edit', to: 'users#edit', as: 'edit_user'
  patch 'user', to: 'users#update', as: 'user_update'
  get 'users', to: 'users#index', as: 'users'
  get 'users/:id', to: 'users#show', as: 'user'
  get 'user', to: 'users#default_show', as: 'user_default'

  # ------------- Wishlist ------------
  get 'user/:user_id/wishlists', to: 'wishlist#index', as: 'user_wishlists'
  post 'user/:user_id/wishlists', to: 'wishlist#create'
  get 'user/:user_id/wishlists/new', to: 'wishlist#new', as: 'new_user_wishlist'
  get 'users/:user_id/wishlists/:id', to: 'wishlist#show', as: 'user_wishlist'

  # Wishlist Items
  resources :items do
    post 'add_to_wishlist', on: :member
  end

  post 'items/:id/add_to_wishlist', to: 'wishlist_items#create', as: 'add_to_wishlist'

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :bigint           not null, primary key
#  apt_num                :integer          default(100)
#  blurb                  :text             default(""), not null
#  card_num               :bigint           default(1000000000000000)
#  city                   :string           default("")
#  confirmation_sent_at   :datetime
#  confirmation_token     :string
#  confirmed_at           :datetime
#  country                :string           default("")
#  current_sign_in_at     :datetime
#  current_sign_in_ip     :string
#  cvc                    :integer          default(999)
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  exp_month              :integer          default(11)
#  exp_year               :integer          default(2029)
#  failed_attempts        :integer          default(0), not null
#  first_name             :string           default("")
#  last_name              :string           default("")
#  last_sign_in_at        :datetime
#  last_sign_in_ip        :string
#  locked_at              :datetime
#  phone                  :string           default("0000000000"), not null
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  sign_in_count          :integer          default(0), not null
#  state                  :string           default("")
#  street_address         :string           default("")
#  unconfirmed_email      :string
#  unlock_token           :string
#  username               :string           default("New User"), not null
#  zip_code               :integer          default(99999)
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#
class User < ApplicationRecord
  
  has_many :wishlists, dependent: :destroy

  before_create :set_defaults
  
  def set_defaults
    self.username ||= generate_unique_username
  end

  def generate_unique_username
    base_username = self.name.parameterize(separator: '_')
    username = base_username.dup
    num = 1

    while self.class.exists?(username: username)
      username = "#{base_username}_#{num}"
      num += 1
    end

    username
  end

  validates :card_num, allow_nil: true, allow_blank: true, format: { with: /\A\d{15,16}\z/, message: "must be a valid credit card number" }
  validates :cvc, allow_nil: true, allow_blank: true, numericality: { only_integer: true }, format: { with: /\A\d{3,4}\z/, message: "must be a valid cvc" }
  validates :exp_month, allow_nil: true, allow_blank: true, format: { with: /\A\d{1,2}\z/, message: "must be a valid month" }, numericality: { greater_than_or_equal_to: 1, less_than_or_equal_to: 12, only_integer: true}
  validates :exp_year, allow_nil: true, allow_blank: true, format: { with: /\A\d{4}\z/, message: "must be a valid year"}, numericality: { greater_than_or_equal_to: Date.today.year, only_integer: true}
  validates :zip_code, allow_nil: true, allow_blank: true, length: { is: 5 }, numericality: { only_integer: true }
  validates :phone, allow_nil: true, allow_blank: true, length: { is: 10 }, numericality: { only_integer: true }

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many(
    :reviews,
    class_name:  'Review',
    foreign_key: 'user_id',
    inverse_of:  :user,
    dependent:   :destroy
  )

  has_many(
    :payments,
    class_name:  'Payment',
    foreign_key: 'user_id',
    inverse_of:  :user,
    dependent:   :destroy
  )

  has_one(
    :cart,
    class_name: 'Cart',
    foreign_key: 'user_id',
    inverse_of:  :user,
    dependent:   :destroy
  )

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

#Calvin Gott -  created the User Contrller class, to have User Actions
    before_action :authenticate_user!

    # List of profiles on the site
    def index
        @users = User.order(:email)
        @current_user = current_user
        render :index
    end

    # this should resolve a weird error that occurs sometimes
    def default_show
      @user = current_user
      @is_me = true

      render :show
    end

    def show
      if current_user
        @wishlists = current_user.wishlists
        @payments = current_user.payments
        @user = User.find(params[:id])
        @is_me = @user.id == current_user.id
        render :show
      else
        @user = User.find(params[:id])
        @is_me = @user.id == current_user.id
        render :show
      end
    end

    def edit
        @user = current_user
        render :edit
    end

    def update
        if current_user.update(user_update_params)
          flash[:success] = 'Updated successfully!'
          redirect_to user_path(current_user)
        else
          flash.now[:error] = 'Your update failed!'
          @user = current_user
          render :edit, status: :unprocessable_entity
        end
    end

    private
    def user_update_params
      params.require(:user).permit(
          :username, 
          :blurb,
          :first_name, 
          :last_name,
          :phone,
          :card_num,
          :cvc,
          :exp_month,
          :exp_year,
          :apt_num,
          :street_address,
          :city,
          :zip_code,
          :state,
          :country
      )
    end
    
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
  <!-- Calvin Gott, Dropdown menu, takes a user to settings page, and then allows them to update personal infomation-->

<h1>Hello <%=@user.first_name%></h1>
<strong>Update your user information here.</strong>
<%= bootstrap_form_with model: @user, url: user_update_path, method: :patch, data: { turbo: false } do |f| %>
  <div class="row">
    <div class="col-sm">
        <h4>User Information</h4>
        <%= f.text_field :username, value: @user.username%>
        <%= f.text_area :blurb, value: @user.blurb%>
    </div>
    <div class="col-sm">
        <h4>Personal Information</h4>
        <%= f.text_field :first_name, value: @user.first_name%>
        <%= f.text_field :last_name, value: @user.last_name%>
        <%= f.text_field :phone, value: @user.phone %>
    </div>
    <div class="col-sm">
        <h4>Billing Information</h4>
        <%= f.number_field :card_num, value: @user.card_num%>
        <%= f.number_field :cvc, value: @user.cvc%>
        <%= f.number_field :exp_month, value: @user.exp_month%>
        <%= f.number_field :exp_year, value: @user.exp_year%>
    </div>
    <div class="col-sm">
        <h4>Shipping Information</h4>
        <%= f.number_field :apt_num, value: @user.apt_num%>
        <%= f.text_field :street_address, value: @user.street_address%>
        <%= f.text_field :city, value: @user.city%>
        <%= f.number_field :zip_code, value: @user.zip_code%>
        <%= f.text_field :state, value: @user.state%>
        <%= f.text_field :country, value: @user.country%>
    </div>
  </div>
  <%= f.submit %>

<% end %>

<%= link_to "Back", user_path(@user), class: 'btn btn-primary pt-2' %>

app/views/users/index.html.erb
<h1> Site Users list </h1>

<table class="table table-hover">
  <thead class="table-dark">
    <tr>
      <th>Name</th>
      <th>Username</th>
      <th>Email</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <% unless user.id == @current_user.id%>
        <tr>
          <td><%= user.last_name%>, <%= user.first_name%></td>
          <td><%= user.username%></td>
          <td><%= user.email%></td>
          <td><%= link_to "View Profile", user_path(user)%></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

app/views/users/show.html.erb
<section style="background-color: #eee;">
  <div class="container py-5">
    <div class="row">
      <div class="col">
      </div>
    </div>

    <div class="row">
      <div class="col-lg-4">
        <div class="card mb-4">
          <div class="card-body text-center">
            <h5 class="my-3">USER: <%= @user.username %> </h5>
            <hr>
            <p class="mb-0">Blurb</p>
            <br>
            <p class="text-muted mb-0"><%= @user.blurb %></p>
            <hr>
            <%if @is_me%>
              <div class="d-flex justify-content-center mb-2">
                <%= link_to "Edit Information", edit_user_path, class: 'btn btn-outline-primary me-1' %>
              </div>
              <div class="d-flex justify-content-center mb-2">
              <%= link_to "Change Credentials", edit_registration_path(@user), class: 'btn btn-outline-primary me-1' %>
              </div>
            <%end%>
          </div>
        </div>
        <%if @is_me%>
          <div class="card mb-4 mb-lg-0">
            <div class="card-body">
              <p class="mb-4"><span class="text-primary font-italic me-1">Order History</p>
              <% if current_user.payments.present? %>
                  <p class = 'text-center'><%= link_to "Payments", payments_path %></p>
              <% else %>
                <p class="text-center">No orders yet</p>
              <% end %> 
            </div>
          </div>
        <%end%>
      </div>
      <div class="col-lg-8">
        <div class="card mb-4">
          <div class="card-body">
            <p class="mb-4"><span class="text-primary font-italic me-1">User Info</p>
            <div class="row">
              <div class="col-sm-3">
                <p class="mb-0">Name</p>
              </div>
              <div class="col-sm-9">
                <p class="text-muted mb-0"><%=@user.first_name%> <%= @user.last_name %></p>
              </div>
            </div>
            <hr>
            <div class="row">
              <div class="col-sm-3">
                <p class="mb-0">Email</p>
              </div>
              <div class="col-sm-9">
                <p class="text-muted mb-0"><%= @user.email %></p>
              </div>
            </div>
            <hr>
            <div class="row">
              <div class="col-sm-3">
                <p class="mb-0">Phone</p>
              </div>
              <div class="col-sm-9">
                <p class="text-muted mb-0"><%= @user.phone %></p>
              </div>
            </div>
            <hr>
            <div class="row">
              <div class="col-sm-3">
                <p class="mb-0">Location</p>
              </div>
              <div class="col-sm-9">
                <p class="text-muted mb-0"><%= @user.city %>, <%= @user.country %></p>
              </div>
            </div>
            <br>            
          </div>
        </div>
          <div class="col-md-6">
            <%if @is_me%>
              <div class="card mb-4 mb-md-0">
                <div class="card-body">
                  <p class="mb-4"><span class="text-primary font-italic me-1">Wishlists</p>
                  <% if current_user.wishlists.present? %>
                    <ul class="list-group">
                      <% current_user.wishlists.each do |wishlist| %>
                        <li class="list-group-item"><%= link_to wishlist.name, user_wishlist_path(wishlist) %></li>
                      <% end %>
                    </ul>
                    <% else %>
                      <p>You don't have any wishlists yet. Start by creating one below.</p>
                    <% end %>
                  <br>
                  <p>
                    <%= link_to "New Wishlist", new_user_wishlist_path(@user), class: "btn btn-secondary"%>
                  </p>
              </div>
            <%end%>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>  