config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#home"
  
  # Pages
  get 'home', to: 'pages#home', as: 'home'
  get 'index', to: 'pages#index'
  get 'boxing_gloves', to: 'pages#boxing_gloves', as: 'boxing_gloves'
  get 'punching_bags', to: 'pages#punching_bags', as: 'punching_bags'
  get 'apparel', to: 'pages#apparel', as: 'apparel'
  get 'search', to: 'pages#search', as: 'search'

  # Item
  get 'items/:id', to: 'item#show', as: 'item'
  get 'items', to: 'items#index', as: 'items'

  # Cart
  get 'cart', to: 'carts#show', as: 'cart'
  post 'items/:id/add_to_cart', to: 'cart_items#create', as: 'add_to_cart'

  # Cart Items
  get '/cart_items/:id/edit', to: 'cart_items#edit', as: 'cart_items_edit'
  delete '/cart_items/:id/', to: 'cart_items#delete', as: 'cart_items'
  patch '/cart_items/:id/', to: 'cart_items#update'

  # Payments
  get 'checkout', to: 'payment#new', as: 'new_payment'
  post 'payments', to: 'payment#create', as: 'create_payment'
  get 'payments/:id', to: 'payment#show', as: 'payment'
  get 'payments', to: 'payment#index', as: 'payments'

  # Reviews
  get 'items/:item_id/reviews', to: 'reviews#index', as: 'item_reviews'
  post 'items/:item_id/reviews', to: 'reviews#create'
  get 'items/:item_id/reviews/new', to: 'reviews#new', as: 'new_item_review'
  get 'items/:item_id/reviews/:id/edit', to: 'reviews#edit', as: 'edit_item_review'
  patch 'item/:item_id/reviews/:id', to: 'reviews#update', as: 'toedit'
  # get 'items/:item_id/reviews', to: 'reviews#show', as: 'item_review'
  delete 'items/:item_id/reviews/:id', to: 'reviews#destroy', as: 'delete_item_review'

  # Users
  get 'user/edit', to: 'users#edit', as: 'edit_user'
  patch 'user', to: 'users#update', as: 'user_update'
  get 'users', to: 'users#index', as: 'users'
  get 'users/:id', to: 'users#show', as: 'user'
  get 'user', to: 'users#default_show', as: 'user_default'

  # ------------- Wishlist ------------
  get 'user/:user_id/wishlists', to: 'wishlist#index', as: 'user_wishlists'
  post 'user/:user_id/wishlists', to: 'wishlist#create'
  get 'user/:user_id/wishlists/new', to: 'wishlist#new', as: 'new_user_wishlist'
  get 'users/:user_id/wishlists/:id', to: 'wishlist#show', as: 'user_wishlist'

  # Wishlist Items
  resources :items do
    post 'add_to_wishlist', on: :member
  end

  post 'items/:id/add_to_wishlist', to: 'wishlist_items#create', as: 'add_to_wishlist'

end

app/views/shared/_flash.html.erb
<% flash.each do |key, message| %>
  <div class="alert <%= alert_class(key) %> alert-dismissible fade show" role="alert">
    <div class="text-center alert-message"><%= message %></div>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
  <!-- Logo/Name -->
    <a class="navbar-brand" href="/">BOXER WORLD</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <!-- Right Side -->
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/">Home</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Categories
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="/boxing_gloves">Boxing Gloves</a></li>
            <li><a class="dropdown-item" href="/punching_bags">Punching Bags</a></li>
            <li><a class="dropdown-item" href="/apparel">Apparel</a></li>
          </ul>
        </li>
      </ul>
      <%= form_tag search_path, html: { class: "d-flex" }, method: :get do %>
          <%= text_field_tag :query, params[:query], placeholder: "Search...", class: 'form-control me-2' %>
      <% end %> 
    </div>
    <!-- Left Side -->
    <!-- Search -->
      
    <div>
    <!-- Cart --> 
    <div>
      <ul class="navbar-nav">
          <% if user_signed_in? %>
          <li class="nav-item">
            <a class="nav-link" href=<%= cart_path %> ><i class="fa-solid fa-cart-shopping fa-lg"></i></a>
          </li>

          <li class="nav-item dropdown">
            <!-- Calvin Gott, Dropdown menu, takes a user to user page, and then allows them to go to necessary pages for Editing-->
            <a class="nav-link" href=<%= user_path(current_user) %>  role="button"><i class='fas fa-user-circle' style='font-size:24px'></i></a>
            <li class="nav-item">
              <%= button_to 'Sign Out', destroy_user_session_path,
                          method: :delete, data: { turbo: false }, class: 'nav-link btn btn-link' %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to 'Sign In', new_user_session_path,
                          class: "nav-link #{active_class(new_user_session_path)} btn btn-link" %>
            </li>
            <li class="nav-item">
              <%= link_to 'Sign Up', new_user_registration_path,
                          class: "nav-link #{active_class(new_user_registration_path)} btn btn-link" %>
            </li>
          <% end %>
        </ul>
      </div>    
    <div>
  </div>
  
</nav>