config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#home"
  
  # Pages
  get 'home', to: 'pages#home', as: 'home'
  get 'index', to: 'pages#index'
  get 'boxing_gloves', to: 'pages#boxing_gloves', as: 'boxing_gloves'
  get 'punching_bags', to: 'pages#punching_bags', as: 'punching_bags'
  get 'apparel', to: 'pages#apparel', as: 'apparel'
  get 'search', to: 'pages#search', as: 'search'

  # Item
  get 'items/:id', to: 'item#show', as: 'item'
  get 'items', to: 'items#index', as: 'items'

  # Cart
  get 'cart', to: 'carts#show', as: 'cart'
  post 'items/:id/add_to_cart', to: 'cart_items#create', as: 'add_to_cart'

  # Cart Items
  get '/cart_items/:id/edit', to: 'cart_items#edit', as: 'cart_items_edit'
  delete '/cart_items/:id/', to: 'cart_items#delete', as: 'cart_items'
  patch '/cart_items/:id/', to: 'cart_items#update'

  # Payments
  get 'checkout', to: 'payment#new', as: 'new_payment'
  post 'payments', to: 'payment#create', as: 'create_payment'
  get 'payments/:id', to: 'payment#show', as: 'payment'
  get 'payments', to: 'payment#index', as: 'payments'

  # Reviews
  get 'items/:item_id/reviews', to: 'reviews#index', as: 'item_reviews'
  post 'items/:item_id/reviews', to: 'reviews#create'
  get 'items/:item_id/reviews/new', to: 'reviews#new', as: 'new_item_review'
  get 'items/:item_id/reviews/:id/edit', to: 'reviews#edit', as: 'edit_item_review'
  patch 'item/:item_id/reviews/:id', to: 'reviews#update', as: 'toedit'
  # get 'items/:item_id/reviews', to: 'reviews#show', as: 'item_review'
  delete 'items/:item_id/reviews/:id', to: 'reviews#destroy', as: 'delete_item_review'

  # Users
  get 'user/edit', to: 'users#edit', as: 'edit_user'
  patch 'user', to: 'users#update', as: 'user_update'
  get 'users', to: 'users#index', as: 'users'
  get 'users/:id', to: 'users#show', as: 'user'
  get 'user', to: 'users#default_show', as: 'user_default'

  # ------------- Wishlist ------------
  get 'user/:user_id/wishlists', to: 'wishlist#index', as: 'user_wishlists'
  post 'user/:user_id/wishlists', to: 'wishlist#create'
  get 'user/:user_id/wishlists/new', to: 'wishlist#new', as: 'new_user_wishlist'
  get 'users/:user_id/wishlists/:id', to: 'wishlist#show', as: 'user_wishlist'

  # Wishlist Items
  resources :items do
    post 'add_to_wishlist', on: :member
  end

  post 'items/:id/add_to_wishlist', to: 'wishlist_items#create', as: 'add_to_wishlist'

end

app/models/cart.rb
# == Schema Information
#
# Table name: carts
#
#  id         :bigint           not null, primary key
#  active     :boolean
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :bigint
#
# Indexes
#
#  index_carts_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class Cart < ApplicationRecord
    belongs_to(
      :user,
      class_name:  'User',
      foreign_key: 'user_id',
      inverse_of:  :cart
    )
    has_many(
      :cart_items,
      class_name:  'CartItem',
      foreign_key: 'cart_id',
      inverse_of:  :cart,
      dependent:   :destroy
  )
    has_many :items, through: :cart_items
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
    before_action :authenticate_user!

    def show
        if current_user.cart.nil?
            current_user.cart = Cart.new
        end
        
        @cart = current_user.cart
        render :show
    end

end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/show.html.erb
<!-- Ken Schnarrs -->

<div class="d-flex justify-content-center align-items-center"> 
    <h1>Ready to check out?</h1>
</div>

<div style="display: flex;">
  <div style="width: 70%;">
    <h3>Cart</h3>
    <%if @cart&.cart_items&.any? %>
      <div style="display: grid; grid-template-columns: repeat(4, 1fr); grid-gap: 10px;" >

          <% total = 0%>

          <!-- This guarantees the cart items are uniquely displayed. -->
            <% unique_items = {} %>
            <% @cart.cart_items.each do |cart_item| %>
              <% if unique_items[cart_item.item_id] %>
                <%unique_items[cart_item.item_id]["quantity"] += cart_item.quantity%>
              <%else%>
                <%cart_item_hash = {
                  "item" => cart_item.item,
                  "quantity" => cart_item.quantity,
                  "cart_item" => cart_item,
                } %>
                <% unique_items[cart_item.item_id] = cart_item_hash %>
              <% end %>
            <% end %>

            <%unique_items.each do |item_id, cart_item_hash|%>
              <%item = cart_item_hash["item"]%>
              <%quantity = cart_item_hash["quantity"]%>
              <%cart_item = cart_item_hash["cart_item"]%>
                <div class="p-3">
                    <div class="card" style="width: 8rem;">
                        <%= link_to image_tag(item.picture, class: 'img-thumbnail', alt: item.name), item_path(item) %>
                        <div class="card-body d-flex justify-content-center align-items-center flex-column">
                            <h5 class="card-title text-center"><%= item.name %></h5>
                            <h6><%=number_to_currency(item.price)%></h6>
                            <p>Amount: <%=quantity%><a href="" class="btn-secondary"></a>
                            <%total = (total + item.price) * quantity%>
                            <div class="row">
                              <div class="col-md-6">
                                <%= button_to cart_items_edit_path(cart_item), method: :get, data: {turbo: false } do %>
                                  <i class="fas fa-edit"></i>
                                <% end %>
                              </div>
                              <div class="col-md-6">
                                <%= button_to cart_items_path(cart_item), method: :delete, data: { confirm: "Are you sure you want to delete this item?", turbo: false } do %>
                                  <i class="fas fa-trash"></i>
                                <% end %>
                              </div>
                            </div>
                        </div>
                    </div>
                </div>
            <% end %>
          </div>
    <%else%>
      <p class="text-danger">You have no items in your cart! Get to shopping to continue on the path of legends.<p>
      <%= link_to 'Home', root_path, class: 'btn btn-outline-primary btn-lg' %>
    <% end %>

  </div>
  <div style="width: 30%;">
    <h3>Total: <%=number_to_currency(total)%></h3>
    <%if @cart&.cart_items&.any? %>
      <div class="card-body d-flex justify-content-center align-items-center flex-column">
        <%= link_to 'CHECKOUT', new_payment_path, class: 'btn btn-outline-success btn-lg mt-5' %>
      </div>
    <% end %>
  </div>
</div>