config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#home"
  
  # Pages
  get 'home', to: 'pages#home', as: 'home'
  get 'index', to: 'pages#index'
  get 'boxing_gloves', to: 'pages#boxing_gloves', as: 'boxing_gloves'
  get 'punching_bags', to: 'pages#punching_bags', as: 'punching_bags'
  get 'apparel', to: 'pages#apparel', as: 'apparel'
  get 'search', to: 'pages#search', as: 'search'

  # Item
  get 'items/:id', to: 'item#show', as: 'item'
  get 'items', to: 'items#index', as: 'items'

  # Cart
  get 'cart', to: 'carts#show', as: 'cart'
  post 'items/:id/add_to_cart', to: 'cart_items#create', as: 'add_to_cart'

  # Cart Items
  get '/cart_items/:id/edit', to: 'cart_items#edit', as: 'cart_items_edit'
  delete '/cart_items/:id/', to: 'cart_items#delete', as: 'cart_items'
  patch '/cart_items/:id/', to: 'cart_items#update'

  # Payments
  get 'checkout', to: 'payment#new', as: 'new_payment'
  post 'payments', to: 'payment#create', as: 'create_payment'
  get 'payments/:id', to: 'payment#show', as: 'payment'
  get 'payments', to: 'payment#index', as: 'payments'

  # Reviews
  get 'items/:item_id/reviews', to: 'reviews#index', as: 'item_reviews'
  post 'items/:item_id/reviews', to: 'reviews#create'
  get 'items/:item_id/reviews/new', to: 'reviews#new', as: 'new_item_review'
  get 'items/:item_id/reviews/:id/edit', to: 'reviews#edit', as: 'edit_item_review'
  patch 'item/:item_id/reviews/:id', to: 'reviews#update', as: 'toedit'
  # get 'items/:item_id/reviews', to: 'reviews#show', as: 'item_review'
  delete 'items/:item_id/reviews/:id', to: 'reviews#destroy', as: 'delete_item_review'

  # Users
  get 'user/edit', to: 'users#edit', as: 'edit_user'
  patch 'user', to: 'users#update', as: 'user_update'
  get 'users', to: 'users#index', as: 'users'
  get 'users/:id', to: 'users#show', as: 'user'
  get 'user', to: 'users#default_show', as: 'user_default'

  # ------------- Wishlist ------------
  get 'user/:user_id/wishlists', to: 'wishlist#index', as: 'user_wishlists'
  post 'user/:user_id/wishlists', to: 'wishlist#create'
  get 'user/:user_id/wishlists/new', to: 'wishlist#new', as: 'new_user_wishlist'
  get 'users/:user_id/wishlists/:id', to: 'wishlist#show', as: 'user_wishlist'

  # Wishlist Items
  resources :items do
    post 'add_to_wishlist', on: :member
  end

  post 'items/:id/add_to_wishlist', to: 'wishlist_items#create', as: 'add_to_wishlist'

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController


    before_action :authenticate_user!, except: [:index]

    before_action :require_permission, except: [:index, :show, :new, :create]

    def require_permission
      @item = Item.find(params[:item_id])
      @review = @item.reviews.find(params[:id])
      if @review.user != current_user
        flash[:error] = 'You do not have permission to do that.'
        redirect_to item_reviews_path(@review)
      end
    end

    # def show
    #     @item = Item.find(params[:item_id])
    #     @review = @item.reviews.find(params[:id])
    #     render :show
    #   end


    def index
        @user = current_user
        @item = Item.find(params[:item_id])
        @reviews = @item.reviews
        render :index
      end



      def new
        @item = Item.find(params[:item_id])
        @review = Review.new
        render :new
      end

      def create
        @item = Item.find(params[:item_id])
        @review = @item.reviews.build(params.require(:review).permit(:rating, :review_text))
        @review.user=current_user
        puts @review.inspect
        if @review.save
          flash[:success] = "Review saved successfully"
          redirect_to item_reviews_url(@item)
        else
          flash.now[:error] = "review could not be saved"
          render :new, status: :unprocessable_entity
        
        
        end
    end


    def edit
      @item = Item.find(params[:item_id])
      @review = @item.reviews.find(params[:id])
      render :edit
    end

    def update
      @item= Item.find(params[:item_id])
      @review = @item.reviews.find(params[:id])
      if @review.update(params.require(:review).permit(:rating, :review_text))
        flash[:success] = "Review updated successfully"
        redirect_to item_reviews_url(@item)
      else
        flash.now[:error] = "Review could not be updated"
        render :edit, status: :unprocessable_entity
      end
    end



    def destroy
      unless current_user.nil?
        @item = Item.find(params[:item_id])
        @review = @item.reviews.find(params[:id])

        if @review.user_id == current_user.id
          @review.destroy
          flash[:success] = "Review deleted successfully"
          @item = Item.find(params[:item_id])
          @reviews = @item.reviews
          render :index, status: :see_other
        else
          flash[:error] = "You do not have permission to do that. (Code 1)"
          @item = Item.find(params[:item_id])
          @reviews = @item.reviews
          render :index, status: :unprocessable_entity
        end
      else
        flash[:error] = "You do not have permission to do that. (Code 2)"
        redirect_to root_path, status: :unprocessable_entity
      end
    end
  



end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/edit.html.erb
<h1>Edit Review</h1>
<%= bootstrap_form_with model: @review, method: :patch, url: toedit_path(@item, @review), data: { turbo: false } do |f| %>
  <%= f.number_field :rating,in: 1.0..10.0%>
  <%= f.text_area :review_text,minlength: 30, maxlength:100, hint:"You can only use 100 characters!" %>
  <%= f.submit %>
<% end %>

<BR>
<p>
  <%= link_to "Cancel", item_reviews_path(@item), class: "btn btn-secondary"%>
</p>

 

app/views/reviews/index.html.erb
<h1><%= @item.name %> | <%= @item.brand %></h1>
<BR><BR>

<h1>Reviews</h1>
<div class = "row">
<table class="table table-striped table-hover">
  <thead class="table-dark">
    <tr>
      <th>Rating</th>
      <th>Comment</th>
      <th>User</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @reviews.each do |review| %>
      <tr>
        <td><strong><%=review.rating %></strong></td>
        <td><%=review.review_text %></td>
        <td><%= link_to review.user.username, user_path(review.user) %></td>
        <td>
        <% unless @user.nil? %>
          <% if review.user.id == @user.id %>
            <%= button_to 'Delete', delete_item_review_path(@item, review), 
              method: :delete, data: { turbo: false }, 
              class: 'btn btn-outline-secondary btn-sm', 
              form: { class: 'd-inline' } 
            %>
          <% end %>
        <% end %>

        </td>

        <td>
        <% unless @user.nil? %>
        <% if review.user.id == @user.id %>
        <%= link_to 'Edit', edit_item_review_path(@item, review), class: 'btn btn-outline-secondary btn-sm' %>
        <% end %>
        <% end %>
        
        </td>
      </tr>
    <% end %>

  
  </tbody>
</table>
</div>

<p>
  <%= link_to " Create New Review", new_item_review_path(@item), class: "btn btn-secondary"%>
</p>

<p>
  <%= link_to 'Back to item', item_path(@item) %>
</p>

app/views/reviews/new.html.erb
<h1>Add a Review</h1>
<%= bootstrap_form_with model: @review, method: :post, url: item_reviews_path(@item), data: { turbo: false } do |f| %>
  <%= f.number_field :rating,in: 1.0..10.0%>
  <%= f.text_area :review_text,minlength: 30, maxlength:100, hint:"You can only use 100 characters!" %>
  <%= f.submit  %>


<% end %>

app/views/reviews/show.etml.erb
<h1>hello</h1>